# Generated by Django 2.2.9 on 2022-06-30 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220630_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'pub_date', 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
