# Generated by Django 2.2.9 on 2022-06-30 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20220630_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['pub_date'], 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
