# Generated by Django 2.2.16 on 2022-12-19 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_follow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
