# Generated by Django 2.2.16 on 2022-12-20 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20221219_1111'),
        ('posts', '0018_auto_20221219_1151'),
    ]

    operations = [
    ]
